- name: launch a compute instance
  hosts: localhost
  tasks:
    - name: launch an instance
      os_server:
        state: present
        auth:
          auth_url: 'https://region:35357/v2.0/'
          username: username
          password: password
          project_name: thisproject
        name: vm1
        region_name: region.geo
        availability_zone: availability
        image: 9302692b-b787-4b52-a3a6-daebb79cb498
        key_name: test
        timeout: 200
        flavor: 101
        security_groups: default
        auto_ip: yes
        meta: "hostname=testhost,group=testgroup"

